apiVersion: v2
name: ska-tmc-testing-low
description: An umbrella Helm chart for SKA-TMC-Low deployment.
type: application
version: 0.1.0
appVersion: 1.16.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
  - name: Jayant Kumbhar
    email: jayant.ska@gmail.com
  - name: Devesh Pandey
    email: devesh.ska@gmail.com
dependencies:
  - name: ska-tango-util
    version: 1.0.7
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tango-base
    version: 1.0.7
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tmc-low
    version: 2.16.0-rc.2
    repository: file://../ska-tmc-low
    alias: tmc-low
  - name: ska-tango-taranta
    version: 2.18.2
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-tango-tangogql
    version: 1.4.8
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-tmc-simulators
    version: 1.14.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tmc-simulators.enabled
