image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE

variables:
  GIT_SUBMODULE_STRATEGY: recursive


cache:
  paths:
    - build

stages:
  - lint
  - build
  - on-demand
  - scaling
  - test
  - integration
  - publish
  - staging
  - pages
  - scan
  - lifecycle

include:
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python-lint.gitlab-ci.yml'

  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'

  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'

  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs-pages.gitlab-ci.yml'

  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/k8s.gitlab-ci.yml'

  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/deploy.integration.gitlab-ci.yml'

  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/deploy.staging.gitlab-ci.yml"

  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'


on-demand-deploy:
  stage: on-demand
  tags:
    - ska-k8s
  variables:
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-on-demand"
    TARANTA_ENABLED: "true"
  script:
    - make cred SERVICE_ACCOUNT=$SERVICE_ACCOUNT
    - '[ -f .make/k8s.mk ] || (echo "File k8s.mk not included in Makefile; exit 1")'
    - make k8s-install-chart
    - make k8s-wait
    - make taranta-link
    - make alarm-handler-configurator-link
  environment:
    name: $CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG
    kubernetes:
      namespace: $KUBE_NAMESPACE
    on_stop: on-demand-destroy
  when: manual
  allow_failure: true


on-demand-destroy:
  stage: on-demand
  tags:
    - ska-k8s
  variables:
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-on-demand"
  script:
    - make cred SERVICE_ACCOUNT=$SERVICE_ACCOUNT
    - '[ -f .make/k8s.mk ] || (echo "File k8s.mk not included in Makefile; exit 1")'
    - make k8s-uninstall-chart
  environment:
    name: $CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG
    kubernetes:
      namespace: $KUBE_NAMESPACE
    action: stop
  when: manual
  allow_failure: true

k8s-test:
  variables:
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA'
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
  before_script:
    - make cred SERVICE_ACCOUNT=$SERVICE_ACCOUNT
    - '[ -f .make/k8s.mk ] || (echo "File k8s.mk not included in Makefile; exit 1")'
    - 'make help | grep k8s-test'
    - make k8s-install-chart
    - make k8s-wait
  after_script:
    - pip3 install -q -U ska-ser-xray
    - XRAY_TEST_RESULT_FILE="build/cucumber.json" make xray-publish

k8s-test-tmc-low-restart:
  extends:
    - k8s-test
  variables:
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-tmc-low-restart'
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-tmc-low-restart"
    MARK: 'SKA_tmc_low_restart'
    SUBARRAY_COMMAND_TIMEOUT: 10
    COUNT: 1
  before_script:
    - make cred SERVICE_ACCOUNT=$SERVICE_ACCOUNT
    - '[ -f .make/k8s.mk ] || (echo "File k8s.mk not included in Makefile; exit 1")'
    - 'make help | grep k8s-test'
    - make k8s-install-chart
    - make k8s-wait
  after_script:
    - pip3 install -q -U ska-ser-xray
    - XRAY_TEST_RESULT_FILE="build/cucumber.json" make xray-publish
  environment:
    name: test/$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-test-tmc-low-restart

stop-k8s-test-tmc-low-restart:
  extends:
    - stop-k8s-test
  variables:
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-tmc-low-restart'

k8s-tmc-scaling:
  stage: scaling
  when: manual
  extends:
    - k8s-test
  tags:
    - ska-staging-tmc
  variables:
    SUBARRAY_COUNT: 4
    COUNT: 1
    KUBE_NAMESPACE: "staging-ska-tmc-low"
    CI_KEEP_NAMESPACE: true
    K8S_TIMEOUT: "1800s"
    TARANTA_ENABLED: "true"
  script:
    - make taranta-link
  environment:
    name: ska-tmc-staging-env
    auto_stop_in: never
    on_stop: stop-k8s-tmc-scaling

stop-k8s-tmc-scaling:
  stage: scaling
  extends:
    - stop-k8s-test
  tags:
    - ska-staging-tmc
  variables:
    KUBE_NAMESPACE: "staging-ska-tmc-low"
  environment:
    name: ska-tmc-staging-env
    action: stop
  when: manual

deploy-integration:
  when: manual
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG'

redeploy-integration:
  when: manual
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG'

info-integration:
  when: manual
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG'

stop-integration:
  when: manual
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG'

#staging
deploy-staging:
  stage: staging
  when: manual
  rules:
    - if: $CI_COMMIT_TAG

redeploy-staging:
  stage: staging
  when: manual
  rules:
    - if: $CI_COMMIT_TAG

info-staging:
  stage: staging
  when: manual
  rules:
    - if: $CI_COMMIT_TAG

stop-staging:
  stage: staging
  when: manual
  rules:
    - if: $CI_COMMIT_TAG
