display: ":0"
xauthority: "~/.Xauthority"

enabled: true

legacy_compatibility: true

system: TM-low
telescope: SKA-low
subsystem: ska-tmc-low

labels:
  app: ska-tmc-low
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG
Values.astroDataVolume: ~
global:
  minikube: false
  astroDataClaim: ~
  tango_host: databaseds-tango-base-test:10000
  #  .Values.global.subarray_count
  # subarray_count, this will be expanded (1 to N inclusive)
  subarray_count: 1

domain: "low-tmc"
##  Order of instances resolution ##
# .Values.deviceServers.<device>.instances
# File, data/<device>.yaml, instances
# deviceServers.cspsubarrayleafnode, deviceServers.sdpsubarrayleafnode,
# deviceServers.subarraynode , deviceServers.mccssubarrayleafnode
subarray_devices:
  - "cspsubarrayleafnode"
  - "sdpsubarrayleafnode"
  - "subarraynode"
  - "mccssubarrayleafnode"

# FQDN details are specific to TMC, shouldn't be overridden in global unless
#  absolutely necessary.
devices_fqdn:
  tmc_subarray_prefix: "low-tmc/subarray"
  csp_subarray_ln_prefix: "low-tmc/subarray-leaf-node-csp/"
  sdp_subarray_ln_prefix: "low-tmc/subarray-leaf-node-sdp/"
  csp_master_ln: "low-tmc/leaf-node-csp/0"
  sdp_master_ln: "low-tmc/leaf-node-sdp/0"
  mccs_master_ln: "low-tmc/leaf-node-mccs/0"
  csp_subarray_prefix: "low-csp/subarray"
  sdp_subarray_prefix: "low-sdp/subarray"
  csp_master: "low-csp/control/0"
  sdp_master: "low-sdp/control/0"
  mccs_master: "low-mccs/control/control"
  mccs_subarray_ln_prefix: "low-tmc/subarray-leaf-node-mccs/"
  mccs_subarray_prefix: "low-mccs/subarray"
  resource_monitor_prefix: "low-tmc/resource-monitor/"

dsconfig:
  configuration_file: data/tmc-low-config.json
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.7
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.10
    pullPolicy: IfNotPresent

centralnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-centralnode
    tag: 0.25.0
    pullPolicy: IfNotPresent

subarraynode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-subarraynode
    tag: 0.47.1
    pullPolicy: IfNotPresent

sdpleafnodes:
  image:
    registry: artefact.skao.int
    image: ska-tmc-sdpleafnodes
    tag: 0.24.3
    pullPolicy: IfNotPresent

cspmasterleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-cspleafnodes
    tag: 0.33.2
    pullPolicy: IfNotPresent

cspsubarrayleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-cspleafnodes
    tag: 0.33.2
    pullPolicy: IfNotPresent

mccsmasterleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-mccsleafnodes
    tag: 0.10.3
    pullPolicy: IfNotPresent

mccssubarrayleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-mccsleafnodes
    tag: 0.10.3
    pullPolicy: IfNotPresent

resource_monitor:
  image:
    registry: artefact.skao.int
    image: ska-tmc-resource-monitor
    tag: 0.3.0
    pullPolicy: IfNotPresent

resources:
  limits:
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 200Mi

deviceServers:
  centralnode:
    enabled: true
    instances: ["01"]
    file: "data/centralnode.yaml"
    SkuidService: "ska-ser-skuid-test-svc.ska-tmc-centralnode.svc.techops.internal.skao.int:9870"
    LivelinessCheckPeriod: 0.5
    EventSubscriptionCheckPeriod: 0.5
    CommandTimeOutDefault: 80
    AssignResourcesInterface: "https://schema.skao.int/ska-low-tmc-assignresources/4.0"
    ReleaseResourcesInterface: "https://schema.skao.int/ska-low-tmc-releaseresources/3.0"
    family: "central-node"
    member: "0"
    IsAutoRecoveryEnabled: "true"

  subarraynode:
    enabled: true
    file: "data/subarraynode.yaml"
    CspAssignResourcesInterfaceURL: "https://schema.skao.int/ska-low-csp-assignresources/3.0"
    CspScanInterfaceURL: "https://schema.skao.int/ska-low-csp-scan/2.0"
    SdpScanInterfaceURL: "https://schema.skao.int/ska-sdp-scan/0.4"
    MccsConfigureInterfaceURL: "https://schema.skao.int/ska-low-mccs-configure/1.0"
    MccsScanInterfaceURL: "https://schema.skao.int/ska-low-mccs-scan/3.0"
    JonesURI: "tango://jones.skao.int/low/stn-beam/1"
    LivelinessCheckPeriod: 0.5
    EventSubscriptionCheckPeriod: 0.5
    CommandTimeOutDefault: 70
    AbortCommandTimeOut: 40
    family: "subarray"
    IsAutoRecoveryEnabled: "true"
    TelmodelSource: "car://gitlab.com/ska-telescope/ska-telmodel-data?main#tmdata"
    TelmodelPath: "instrument/ska1_low/layout/low-layout.json"
    MccsReleaseInterfaceURL: "https://schema.skatelescope.org/ska-low-mccs-controller-release/2.0"


  sdpsubarrayleafnode:
    enabled: true
    file: "data/sdpsubarrayleafnode.yaml"
    CommandTimeOutDefault: 50
    AdapterTimeOut: 2
    LivelinessCheckPeriod: 0.5
    EventSubscriptionCheckPeriod: 0.5
    SDPSubarrayAdminModeEnabled: true
    family: "subarray-leaf-node-sdp"

  sdpmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/sdpmasterleafnode.yaml"
    AdapterTimeOut: 2
    LivelinessCheckPeriod: 0.5
    EventSubscriptionCheckPeriod: 0.5
    SDPMasterAdminModeEnabled: true
    family: "leaf-node-sdp"
    member: "0"

  cspmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/cspmasterleafnode.yaml"
    AdapterTimeOut: 2.0
    LivelinessCheckPeriod: 0.5
    EventSubscriptionCheckPeriod: 0.5
    family: "leaf-node-csp"
    member: "0"

  mccsmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/mccsmasterleafnode.yaml"
    CommandTimeOutDefault: 50
    LivelinessCheckPeriod: 0.5
    EventSubscriptionCheckPeriod: 0.5
    AdapterTimeOut: 2.0
    family: "leaf-node-mccs"
    member: "0"

  cspsubarrayleafnode:
    enabled: true
    file: "data/cspsubarrayleafnode.yaml"
    TelmodelSource: gitlab://gitlab.com/ska-telescope/ska-telmodel-data?main#tmdata
    TelmodelPath: instrument/ska1_low/layout/low-layout.json
    DelayCadence: 300.0
    DelayValidityPeriod: 600.0
    DelayModelTimeInAdvance: 600
    PSTDelayCadence: 300.0
    PSTDelayValidityPeriod: 600.0
    PSTDelayModelTimeInAdvance: 600
    CommandTimeOutDefault: 50
    AdapterTimeOut: 2.0
    LivelinessCheckPeriod: 0.5
    EventSubscriptionCheckPeriod: 0.5
    family: "subarray-leaf-node-csp"

  mccssubarrayleafnode:
    enabled: true
    file: "data/mccssubarrayleafnode.yaml"
    LivelinessCheckPeriod: 0.5
    EventSubscriptionCheckPeriod: 0.5
    CommandTimeOutDefault: 50
    AdapterTimeOut: 2.0
    family: "subarray-leaf-node-mccs"

  resourcemonitor:
    enabled: true
    instances: [ "01" ]
    file: "data/resourcemonitor.yaml"
    LivelinessCheckPeriod: 0.5
    EventSubscriptionCheckPeriod: 0.5
    family: "resource-monitor"

  mocks:
    enabled: false
    file: "data/mocks.yaml"
    is_simulated:
      sdp: false
      csp: false
      mccs: false

nodeSelector: {}

affinity: {}

tolerations: []
